name: firecrawl

x-common-service: &common-service
  build: apps/api
  ulimits:
    nofile: { soft: 65535, hard: 65535 }
  networks: [backend]
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-common-env: &common-env
  # ---- Internal service wiring (keep defaults unless you change ports) ----
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}
  REDIS_RATE_LIMIT_URL: ${REDIS_RATE_LIMIT_URL:-redis://redis:6379}
  PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:${PLAYWRIGHT_PORT:-3000}/scrape}

  # ---- Auth OFF (Firecrawl self-host uses Supabase if you ever enable it) ----
  USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}

  # ---- AI (OpenAI) ----
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL}
  MODEL_NAME: ${MODEL_NAME}
  MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME}

  # ---- Admin / Logs ----
  BULL_AUTH_KEY: ${BULL_AUTH_KEY}
  LOGGING_LEVEL: ${LOGGING_LEVEL}

services:
  playwright-service:
    build: apps/playwright-service-ts
    environment:
      PORT: ${PLAYWRIGHT_PORT:-3000}
      BLOCK_MEDIA: ${BLOCK_MEDIA}
    networks: [backend]
    # (No host port by default; API calls it via Docker network)

  api:
    <<: *common-service
    environment:
      <<: *common-env
      HOST: ${HOST:-0.0.0.0}
      PORT: ${INTERNAL_PORT:-3002}
      FLY_PROCESS_GROUP: app
      ENV: local
    depends_on: [redis, playwright-service]
    # Expose API by host port (no Traefik labels). Change via env only.
    ports:
      - "${API_HOST_PORT:-3002}:${INTERNAL_PORT:-3002}"
    command: ["pnpm","run","start:production"]

  worker:
    <<: *common-service
    environment:
      <<: *common-env
      FLY_PROCESS_GROUP: worker
      ENV: local
    depends_on: [redis, playwright-service, api]
    command: ["pnpm","run","workers"]

  redis:
    image: redis:alpine
    command: ["redis-server","--bind","${REDIS_BIND:-0.0.0.0}","--port","${REDIS_PORT:-6379}"]
    networks: [backend]
    # Internal only (no host port). API/worker reach at redis:6379

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [backend]
    # Optional host access for tools (pgAdmin). Set POSTGRES_HOST_PORT or leave empty to skip.
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:${POSTGRES_CONTAINER_PORT:-5432}"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
